# group-name/instance-name. Should always be two levels deep.
cra/default-js:
  name: "Create React App (Javascript)"
  script: "npx create-react-app ."
  expected:
    framework: "@storybook/cra"
    renderer: "@storybook/react"
    builder: "@storybook/builder-webpack5"

cra/default-ts:
  name: "Create React App (Typescript)"
  script: "npx create-react-app . --template typescript"
  expected:
    framework: "@storybook/cra"
    renderer: "@storybook/react"
    builder: "@storybook/builder-webpack5"