[build]
  publish = "code/built-storybooks"
  command = "yarn task --task compile --start-from=auto --no-link && cd code && yarn build-storybooks --all"
[build.environment]
  NODE_VERSION = "16"
  YARN_VERSION = "1.22.10"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
