name: Unit tests

on: [push]

jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-2-cache-v1-${{ hashFiles('**/yarn.lock') }}
    - name: install, bootstrap
      run: |
        yarn install --immutable
        yarn bootstrap --core
    - name: test
      run: |
        yarn test --runInBand --ci
