name: Unit tests

on: [push]

jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: build-v2-${{ hashFiles('**/yarn.lock') }}
    - name: install, bootstrap
      run: |
        yarn bootstrap --core
    - name: test
      run: |
        yarn test --core
